program gestao;

uses
  {$IFDEF DEBUG}
  {$ENDIF }
  uniGUIISAPI,
  MidasLib,
  Forms,
  ServerModule in 'ServerModule.pas' {USM: TUniGUIServerModule},
  Main in 'Main.pas' {MainForm: TUniForm},
  MainModule in 'MainModule.pas' {UMM: TUniGUIMainModule},
  LoginFrm in 'LoginFrm.pas' {UniLogin: TUniLoginForm},
  CatribEntity in 'framework\CatribEntity.pas',
  GenericDao in 'framework\GenericDao.pas',
  Md5 in 'Function\Md5.pas',
  base_form in 'repository\base_form.pas' {BaseForm: TUniForm},
  openForms in 'function\openForms.pas',
  base_module in 'repository\base_module.pas' {BaseModule: TUniFrame},
  midia_module in 'modules\midia_module.pas' {MidiaModule: TUniFrame},
  base_registry in 'repository\base_registry.pas' {BaseRegistry: TUniForm},
  fm_BaseFrame in 'frames\fm_BaseFrame.pas' {FmBaseFrame: TUniFrame},
  fm_CountryStateCity in 'frames\fm_CountryStateCity.pas' {FmCountryStateCity: TUniFrame},
  fm_Address in 'frames\fm_Address.pas' {FmAddress: TUniFrame},
  cad_entity in 'files\cad_entity.pas' {CadEntity: TUniForm},
  cad_country in 'files\cad_country.pas' {CadCountry: TUniForm},
  cad_state in 'files\cad_state.pas' {CadState: TUniForm},
  fm_country in 'frames\fm_country.pas' {FmCountry: TUniFrame},
  fm_state in 'frames\fm_state.pas' {FmState: TUniFrame},
  fm_city in 'frames\fm_city.pas' {FmCity: TUniFrame},
  cad_city in 'files\cad_city.pas' {CadCity: TUniForm},
  cad_linebusiness in 'files\cad_linebusiness.pas' {CadLinebusiness: TUniForm},
  fm_lineBusiness in 'frames\fm_lineBusiness.pas' {fmLineBusiness: TUniFrame},
  pes_cnpjOnLine in 'features\pes_cnpjOnLine.pas' {PesCnpjOnLine: TUniForm},
  pes_cepLogradouro in 'features\pes_cepLogradouro.pas' {PesCepLogradouro: TUniForm},
  cad_entity_fiscal in 'files\cad_entity_fiscal.pas' {CadEntityFiscal: TUniForm},
  msg_form in 'repository\msg_form.pas' {MsgForm: TUniForm},
  GenericEntity in 'framework\GenericEntity.pas',
  cad_customer in 'files\cad_customer.pas' {CadCustomer: TUniForm},
  fm_Salesman in 'frames\fm_Salesman.pas' {FmSalesman: TUniFrame},
  adm_module in 'modules\adm_module.pas' {AdmModule: TUniFrame},
  purchase_module in 'modules\purchase_module.pas' {PurchaseModule: TUniFrame},
  stock_module in 'modules\stock_module.pas' {StockModule: TUniFrame},
  builder_module in 'modules\builder_module.pas' {BuilderModule: TUniFrame},
  fm_carrier in 'frames\fm_carrier.pas' {FmCarrier: TUniFrame},
  cad_user in 'files\cad_user.pas' {CadUser: TUniForm},
  cad_provider in 'files\cad_provider.pas' {CadProvider: TUniForm},
  cad_payment_types in 'files\cad_payment_types.pas' {CadPaymentTypes: TUniForm},
  cad_brand in 'files\cad_brand.pas' {CadBrand: TUniForm},
  cad_package in 'files\cad_package.pas' {CadPackage: TUniForm},
  cad_measure in 'files\cad_measure.pas' {CadMeasure: TUniForm},
  cad_product in 'files\cad_product.pas' {CadProduct: TUniForm},
  fm_category in 'frames\fm_category.pas' {FmCategory: TUniFrame},
  fm_brand in 'frames\fm_brand.pas' {FmBrand: TUniFrame},
  cad_merchandise in 'files\cad_merchandise.pas' {CadMerchandise: TUniForm},
  fm_package in 'frames\fm_package.pas' {FmPackage: TUniFrame},
  fm_measure in 'frames\fm_measure.pas' {FmMeasure: TUniFrame},
  cad_color in 'files\cad_color.pas' {CadColor: TUniForm},
  fm_color in 'frames\fm_color.pas' {FmColor: TUniFrame},
  tas_changepassword in 'tasks\tas_changepassword.pas' {TasChangepassword: TUniForm},
  base_search in 'repository\base_search.pas' {BaseSearch: TUniForm},
  sea_brand in 'files\sea_brand.pas' {SeaBrand: TUniForm},
  sea_city in 'files\sea_city.pas' {SeaCity: TUniForm},
  sea_color in 'files\sea_color.pas' {SeaColor: TUniForm},
  sea_country in 'files\sea_country.pas' {SeaCountry: TUniForm},
  sea_linebusiness in 'files\sea_linebusiness.pas' {SeaLinebusiness: TUniForm},
  sea_measure in 'files\sea_measure.pas' {SeaMeasure: TUniForm},
  sea_package in 'files\sea_package.pas' {SeaPackage: TUniForm},
  sea_payment_types in 'files\sea_payment_types.pas' {SeaPaymentTypes: TUniForm},
  sea_state in 'files\sea_state.pas' {SeaState: TUniForm},
  sea_entity in 'files\sea_entity.pas' {SeaEntity: TUniForm},
  sea_entity_fiscal in 'files\sea_entity_fiscal.pas' {SeaEntityFiscal: TUniForm},
  sea_product in 'files\sea_product.pas' {SeaProduct: TUniForm},
  sea_merchandise in 'files\sea_merchandise.pas' {SeaMerchandise: TUniForm},
  sea_customer in 'files\sea_customer.pas' {SeaCustomer: TUniForm},
  sea_provider in 'files\sea_provider.pas' {SeaProvider: TUniForm},
  sea_carrier in 'files\sea_carrier.pas' {SeaCarrier: TUniForm},
  cad_carrier in 'files\cad_carrier.pas' {CadCarrier: TUniForm},
  cad_price_list in 'files\cad_price_list.pas' {CadPriceList: TUniForm},
  cad_stock_list in 'files\cad_stock_list.pas' {CadStockList: TUniForm},
  sea_stock_list in 'files\sea_stock_list.pas' {SeaStockList: TUniForm},
  sea_price_list in 'files\sea_price_list.pas' {SeaPriceList: TUniForm},
  tas_order in 'tasks\tas_order.pas' {TasOrder: TUniForm},
  sea_order in 'files\sea_order.pas' {SeaOrder: TUniForm},
  tas_xml_import_nfe in 'tasks\tas_xml_import_nfe.pas' {TasXmlImportNfe: TUniForm},
  cad_module in 'files\cad_module.pas' {CadModule: TUniForm},
  sea_module in 'files\sea_module.pas' {SeaModule: TUniForm},
  super_module in 'modules\super_module.pas' {SuperModule: TUniFrame},
  cad_interface in 'files\cad_interface.pas' {CadInterface: TUniForm},
  sea_interface in 'files\sea_interface.pas' {SeaInterface: TUniForm},
  cad_privilege in 'files\cad_privilege.pas' {CadPrivilege: TUniForm},
  sea_privilege in 'files\sea_privilege.pas' {SeaPrivilege: TUniForm},
  tas_in_out_product in 'tasks\tas_in_out_product.pas' {TasInOutProduct: TUniForm},
  tas_order_purchase in 'tasks\tas_order_purchase.pas' {TasOrderPurchase: TUniForm},
  tas_nf in 'tasks\tas_nf.pas' {TasNf: TUniForm},
  tas_nf_55 in 'tasks\tas_nf_55.pas' {TasNf1: TUniForm},
  tas_nf_65 in 'tasks\tas_nf_65.pas' {TasNf65: TUniForm},
  fm_cfop in 'frames\fm_cfop.pas' {FmCFOP: TUniFrame},
  fm_provider in 'frames\fm_provider.pas' {FmProvider: TUniFrame},
  fm_payment_type in 'frames\fm_payment_type.pas' {fmPaymentType: TUniFrame},
  sea_order_purchase in 'tasks\sea_order_purchase.pas' {SeaOrderPurchase: TUniForm},
  cad_agency in 'files\cad_agency.pas' {CadAgency: TUniForm},
  cad_broadcaster in 'files\cad_broadcaster.pas' {CadBroadCaster: TUniForm},
  cad_advertiser in 'files\cad_advertiser.pas' {CadAdvertiser: TUniForm},
  sea_agency in 'files\sea_agency.pas' {SeaAgency: TUniForm},
  sea_broadcaster in 'files\sea_broadcaster.pas' {SeaBroadcaster: TUniForm},
  sea_advertiser in 'files\sea_advertiser.pas' {SeaAdvertiser: TUniForm},
  cad_med_pos_prog in 'files\cad_med_pos_prog.pas' {CadMedPosProg: TUniForm},
  sea_med_pos_prog in 'files\sea_med_pos_prog.pas' {SeaMedPosProg: TUniForm},
  cad_med_material in 'files\cad_med_material.pas' {CadMedMaterial: TUniForm},
  sea_med_material in 'files\sea_med_material.pas' {SeaMedMaterial: TUniForm},
  tas_order_production_items_mp in 'tasks\tas_order_production_items_mp.pas' {TasOrderProductionItemsMp: TUniForm},
  cad_tax_icms_nr in 'files\cad_tax_icms_nr.pas' {CadTaxIcmsNr: TUniForm},
  sea_tax_icms_nr in 'files\sea_tax_icms_nr.pas' {SeaTaxIcmsNr: TUniForm},
  sea_discharge_icms in 'files\sea_discharge_icms.pas' {SeadischargeIcms: TUniForm},
  cad_discharge_icms in 'files\cad_discharge_icms.pas' {CadDischargeIcms: TUniForm},
  fm_discharge_icms in 'frames\fm_discharge_icms.pas' {FmDischargeIcms: TUniFrame},
  sea_tax_icms_sn in 'files\sea_tax_icms_sn.pas' {SeaTaxIcmsSn: TUniForm},
  cad_tax_icms_sn in 'files\cad_tax_icms_sn.pas' {CadTaxIcmsSN: TUniForm},
  sea_deter_base_tax_icms in 'files\sea_deter_base_tax_icms.pas' {SeaDeterBaseTaxIcms: TUniForm},
  cad_deter_base_tax_icms in 'files\cad_deter_base_tax_icms.pas' {CadDeterBaseTaxIcms: TUniForm},
  fm_deter_base_tax_icms in 'frames\fm_deter_base_tax_icms.pas' {FmDeterBaseTaxIcms: TUniFrame},
  cad_tax_ipi in 'files\cad_tax_ipi.pas' {cadTaxIpi: TUniForm},
  sea_tax_ipi in 'files\sea_tax_ipi.pas' {SeaTaxIpi: TUniForm},
  fm_tax_ipi in 'frames\fm_tax_ipi.pas' {FmTaxIpi: TUniFrame},
  cad_tax_pis in 'files\cad_tax_pis.pas' {cadTaxPis: TUniForm},
  sea_tax_pis in 'files\sea_tax_pis.pas' {SeaTaxPis: TUniForm},
  fm_tax_pis in 'frames\fm_tax_pis.pas' {FmTaxPis: TUniFrame},
  cad_observation in 'files\cad_observation.pas' {CadObservation: TUniForm},
  sea_observation in 'files\sea_observation.pas' {SeaObservation: TUniForm},
  fm_observation in 'frames\fm_observation.pas' {FmObservation: TUniFrame},
  cad_deter_base_tax_icms_st in 'files\cad_deter_base_tax_icms_st.pas' {CadDeterBaseTaxIcmsST: TUniForm},
  sea_deter_base_tax_icms_st in 'files\sea_deter_base_tax_icms_st.pas' {SeaDeterBaseTaxIcmsST: TUniForm},
  fm_deter_base_tax_icms_st in 'frames\fm_deter_base_tax_icms_st.pas' {FmDeterBaseTaxIcmsST: TUniFrame},
  cad_cfop in 'files\cad_cfop.pas' {CadCfop: TUniForm},
  sea_cfop in 'files\sea_cfop.pas' {SeaCfop: TUniForm},
  sea_tax_cofins in 'files\sea_tax_cofins.pas' {SeaTaxCofins: TUniForm},
  cad_tax_ruler in 'files\cad_tax_ruler.pas' {CadTaxRuler: TUniForm},
  fm_tax_icms_sn in 'frames\fm_tax_icms_sn.pas' {FmTaxIcmsSn: TUniFrame},
  fm_tax_cofins in 'frames\fm_tax_cofins.pas' {FmTaxCofins: TUniFrame},
  fm_tax_icms_nr in 'frames\fm_tax_icms_nr.pas' {FmTaxIcmsNr: TUniFrame},
  fm_agency in 'frames\fm_agency.pas' {FmAgency: TUniFrame},
  fm_broadcaster in 'frames\fm_broadcaster.pas' {FmBroadcaster: TUniFrame},
  fm_advertiser in 'frames\fm_advertiser.pas' {FmAdvertiser: TUniFrame},
  tas_order_pi_item in 'tasks\tas_order_pi_item.pas' {TasOrderPiItem: TUniForm},
  fm_med_material in 'frames\fm_med_material.pas' {FmMedMaterial: TUniFrame},
  fm_med_pos_prog in 'frames\fm_med_pos_prog.pas' {FmMedPosProg: TUniFrame},
  tas_order_pi_jr in 'tasks\tas_order_pi_jr.pas' {TasOrderPiJr: TUniForm},
  tas_order_pi_rt in 'tasks\tas_order_pi_rt.pas' {TasOrderPiRt: TUniForm},
  UnGestao in 'function\UnGestao.pas',
  sea_tax_ruler in 'files\sea_tax_ruler.pas' {SeaTaxRuler: TUniForm},
  cad_collaborator in 'files\cad_collaborator.pas' {CadCollaborator: TUniForm},
  sea_collaborator in 'files\sea_collaborator.pas' {SeaCollaborator: TUniForm},
  tas_to_invoice in 'tasks\tas_to_invoice.pas' {TasToInvoice: TUniForm},
  employee_module in 'modules\employee_module.pas' {EmployeeModule: TUniFrame},
  sea_salesman in 'files\sea_salesman.pas' {SeaSalesman: TUniForm},
  tas_order_job in 'tasks\tas_order_job.pas' {TasOrderJob: TUniForm},
  tas_order_packing in 'tasks\tas_order_packing.pas' {TasOrderPacking: TUniForm},
  tas_order_production in 'tasks\tas_order_production.pas' {TasOrderProduction: TUniForm},
  fm_entity in 'frames\fm_entity.pas' {FmEntity: TUniFrame},
  fm_situation in 'frames\fm_situation.pas' {FmSituation: TUniFrame},
  fm_customer in 'frames\fm_customer.pas' {FmCustomer: TUniFrame},
  sea_order_packing in 'files\sea_order_packing.pas' {SeaOrderPacking: TUniForm},
  sea_situation in 'files\sea_situation.pas' {SeaSituation: TUniForm},
  fm_merchandise in 'frames\fm_merchandise.pas' {FmMerchandise: TUniFrame},
  tas_order_pi in 'tasks\tas_order_pi.pas' {TasOrderPi: TUniForm},
  sea_order_pi in 'files\sea_order_pi.pas' {SeaOrderPi: TUniForm},
  sea_order_production in 'files\sea_order_production.pas' {SeaOrderProduction: TUniForm},
  sea_order_job in 'files\sea_order_job.pas' {SeaOrderJob: TUniForm},
  fm_stock_list in 'frames\fm_stock_list.pas' {FmStockList: TUniFrame},
  base_frame_List in 'repository\base_frame_List.pas' {BaseFrameList: TUniFrame},
  tas_order_sale in 'tasks\tas_order_sale.pas' {TasOrderSale: TUniForm},
  sea_order_sale in 'files\sea_order_sale.pas' {SeaOrderSale: TUniForm},
  sale_module in 'modules\sale_module.pas' {SaleModule: TUniFrame},
  tas_order_items_job in 'tasks\tas_order_items_job.pas' {TasOrderItemsJob: TUniForm},
  fm_order_items in 'frames\fm_order_items.pas' {FmOrderItems: TUniFrame},
  fm_order_items_job in 'frames\fm_order_items_job.pas' {FmOrderItemsJob: TUniFrame},
  fm_order_items_sale in 'frames\fm_order_items_sale.pas' {FmOrderItemsSale: TUniFrame},
  fm_order_items_purchase in 'frames\fm_order_items_purchase.pas' {FmOrderItemsPurchase: TUniFrame},
  fm_order_items_packing in 'frames\fm_order_items_packing.pas' {FmOrderItemsPacking: TUniFrame},
  fm_order_items_production in 'frames\fm_order_items_production.pas' {FmOrderItemsProduction: TUniFrame},
  sea_order_stock_transfer in 'files\sea_order_stock_transfer.pas' {SeaOrderStockTransfer: TUniForm},
  fm_entity_fiscal in 'frames\fm_entity_fiscal.pas' {FmEntityFiscal: TUniFrame},
  fm_order_items_stock_adjust in 'frames\fm_order_items_stock_adjust.pas' {FmOrderItemsStockAdjust: TUniFrame},
  sea_order_Stock_Adjust in 'files\sea_order_Stock_Adjust.pas' {SeaOrderStockAdjust: TUniForm},
  tas_order_stock_adjust in 'tasks\tas_order_stock_adjust.pas' {TasOrderStockAdjust: TUniForm},
  tas_order_stock_transfer in 'tasks\tas_order_stock_transfer.pas' {TasOrderStockTransfer: TUniForm},
  tas_config_nfe_55 in 'tasks\tas_config_nfe_55.pas' {TasConfigNfe55: TUniForm},
  tas_config_nfe_65 in 'tasks\tas_config_nfe_65.pas' {TasConfigNfe65: TUniForm},
  sea_invoice_merchandise in 'files\sea_invoice_merchandise.pas' {SeaInvoiceMerchandise: TUniForm},
  cad_institution in 'files\cad_institution.pas' {CadInstitution: TUniForm},
  sea_institution in 'files\sea_institution.pas' {SeaInstitution: TUniForm},
  sea_ncm in 'files\sea_ncm.pas' {SeaNcm: TUniForm},
  sea_cest in 'files\sea_cest.pas' {SeaCest: TUniForm},
  sea_address_delivery in 'files\sea_address_delivery.pas' {SeaAddressDelivery: TUniForm},
  base_list_Registry in 'repository\base_list_Registry.pas' {BaseListRegistry: TUniForm},
  cad_merchandise_has_self in 'files\cad_merchandise_has_self.pas' {CadMerchandiseHasSelf: TUniForm},
  fm_address_delivery in 'frames\fm_address_delivery.pas' {FmAdressDelivery: TUniFrame},
  cad_contact in 'files\cad_contact.pas' {CadContact: TUniForm},
  cad_financial_plans in 'files\cad_financial_plans.pas' {CadFinancialPlans: TUniForm},
  cad_category in 'files\cad_category.pas' {CadCategory: TUniForm},
  tas_order_list_to_buy in 'tasks\tas_order_list_to_buy.pas' {TasOrderListToBuy: TUniForm},
  sea_contact in 'files\sea_contact.pas' {SeaContact: TUniForm},
  rep_viewer in 'reports\rep_viewer.pas' {RepViewer: TUniForm},
  openReports in 'function\openReports.pas',
  fm_order_items_stock_transfer in 'frames\fm_order_items_stock_transfer.pas' {FmOrderItemsStockTransfer: TUniFrame},
  fm_Installment_open in 'frames\fm_Installment_open.pas' {FmInstallmentOpen: TUniFrame},
  tas_order_list_to_delivery in 'tasks\tas_order_list_to_delivery.pas' {TasOrderListToDelivery: TUniForm},
  tas_order_budget_item_jr in 'tasks\tas_order_budget_item_jr.pas' {TasOrderBudgetItemJr: TUniForm},
  tas_order_budget_item_pi_rt in 'tasks\tas_order_budget_item_pi_rt.pas' {TasOrderBudgetItemPiRt: TUniForm},
  cad_extintor in 'files\cad_extintor.pas' {CadExtintor: TUniForm},
  sea_extintor in 'files\sea_extintor.pas' {SeaExtintor: TUniForm},
  tas_financial in 'tasks\tas_financial.pas' {TasFinancial: TUniForm},
  tas_financial_bills in 'tasks\tas_financial_bills.pas' {TasFinancialBills: TUniForm},
  financial_bills_module in 'modules\financial_bills_module.pas' {FinancialBillsModule: TUniFrame},
  financial_payment_module in 'modules\financial_payment_module.pas' {FinancialPaymentModule: TUniFrame},
  tas_financial_payment in 'tasks\tas_financial_payment.pas' {TasFinancialPayment: TUniForm},
  extintor_module in 'modules\extintor_module.pas' {ExtintorModule: TUniFrame},
  bank_module in 'modules\bank_module.pas' {BankModule: TUniFrame},
  cad_bank in 'files\cad_bank.pas' {CadBank: TUniForm},
  sea_bank in 'files\sea_bank.pas' {SeaBank: TUniForm},
  fm_bank in 'frames\fm_bank.pas' {FmBank: TUniFrame},
  cad_bank_account in 'files\cad_bank_account.pas' {CadBankAccount: TUniForm},
  sea_bank_account in 'files\sea_bank_account.pas' {SeaBankAccount: TUniForm},
  uReportCC in 'restClient\apiReport\uReportCC.pas',
  uReportCM in 'restClient\report\uReportCM.pas' {CM: TDataModule},
  fm_freight_mode in 'frames\fm_freight_mode.pas' {fmFreightMode: TUniFrame},
  cad_bank_historic in 'files\cad_bank_historic.pas' {CadBankHistoric: TUniForm},
  sea_bank_historic in 'files\sea_bank_historic.pas' {SeaBankHistoric: TUniForm},
  ClientProxy in 'restClient\nfe\ClientProxy.pas',
  tas_msg_process in 'tasks\tas_msg_process.pas' {TasMsgProcess: TUniForm},
  cad_bank_charge_ticket in 'files\cad_bank_charge_ticket.pas' {CadBankChargeTicket: TUniForm},
  sea_bank_charge_ticket in 'files\sea_bank_charge_ticket.pas' {SeaBankChargeTicket: TUniForm},
  cad_bank_charge_kind in 'files\cad_bank_charge_kind.pas' {CadBankChargeKind: TUniForm},
  sea_bank_charge_kind in 'files\sea_bank_charge_kind.pas' {SeaBankChargeKind: TUniForm},
  fm_bank_account in 'frames\fm_bank_account.pas' {FmBankAccount: TUniFrame},
  fm_bank_charge_ticket in 'frames\fm_bank_charge_ticket.pas' {FmBankChargeTicket: TUniFrame},
  fm_bank_charge_kind in 'frames\fm_bank_charge_kind.pas' {FmBankChargeKind: TUniFrame},
  cad_bank_charge_slip in 'files\cad_bank_charge_slip.pas' {CadBankChargeSlip: TUniForm},
  sea_bank_charge_slip in 'files\sea_bank_charge_slip.pas' {SeaBankChargeSlip: TUniForm},
  cad_accounting in 'files\cad_accounting.pas' {CadAccounting: TUniForm},
  sea_accounting in 'files\sea_accounting.pas' {SeaAccounting: TUniForm},
  sea_order_budget_pi in 'files\sea_order_budget_pi.pas' {SeaOrderBudgetPi: TUniForm},
  tas_order_budget_pi in 'tasks\tas_order_budget_pi.pas' {TasOrderBudgetPi: TUniForm},
  tas_cashier in 'tasks\tas_cashier.pas' {TasCashier: TUniForm},
  cashier_module in 'modules\cashier_module.pas' {CashierModule: TUniFrame},
  tas_order_budget_item_pi_jr in 'tasks\tas_order_budget_item_pi_jr.pas' {TasOrderBudgetItemPiJr: TUniForm},
  tas_check_ctrl in 'tasks\tas_check_ctrl.pas' {TasCheckCtrl: TUniForm},
  sea_check_ctrl in 'tasks\sea_check_ctrl.pas' {SeaCheckCtrl: TUniForm},
  tas_useful_phone in 'tasks\tas_useful_phone.pas' {TasUsefulPhone: TUniForm},
  sea_financial_statement in 'files\sea_financial_statement.pas' {SeaFinancialStatement: TUniForm},
  tas_technical_assistance in 'tasks\tas_technical_assistance.pas' {TasTechnicalAssistance: TUniForm},
  sea_technical_assistance in 'tasks\sea_technical_assistance.pas' {SeaTechnicalAssistance: TUniForm},
  tas_set_price in 'tasks\tas_set_price.pas' {TasSetPrice: TUniForm},
  fm_price_list in 'frames\fm_price_list.pas' {FmPriceList: TUniFrame},
  cad_ext_agent in 'files\cad_ext_agent.pas' {CadExtAgent: TUniForm},
  sea_ext_agent in 'files\sea_ext_agent.pas' {SeaExtAgent: TUniForm},
  fm_product in 'frames\fm_product.pas' {FmProduct: TUniFrame},
  fm_ext_agent in 'frames\fm_ext_agent.pas' {FmExtAgent: TUniFrame},
  cad_ext_kind in 'files\cad_ext_kind.pas' {CadExtKind: TUniForm},
  sea_ext_kind in 'files\sea_ext_kind.pas' {SeaExtKind: TUniForm},
  cad_ext_tester in 'files\cad_ext_tester.pas' {CadExtTester: TUniForm},
  sea_ext_tester in 'files\sea_ext_tester.pas' {SeaExtTester: TUniForm},
  cad_ext_motive in 'files\cad_ext_motive.pas' {CadExtMotive: TUniForm},
  sea_ext_motive in 'files\sea_ext_motive.pas' {SeaExtMotive: TUniForm},
  cad_ext_seal in 'files\cad_ext_seal.pas' {CadExtSeal: TUniForm},
  sea_ext_seal in 'files\sea_ext_seal.pas' {SeaExtSeal: TUniForm},
  cad_service in 'files\cad_service.pas' {CadService: TUniForm},
  sea_ext_maintenance in 'tasks\sea_ext_maintenance.pas' {SeaExtMaintenance: TUniForm},
  tas_ext_maintenance in 'tasks\tas_ext_maintenance.pas' {TasExtMaintenance: TUniForm},
  fm_address_list in 'frames\fm_address_list.pas' {FmAddressList: TUniFrame},
  fm_ext_level in 'frames\fm_ext_level.pas' {FmExtLevel: TUniFrame},
  tas_ext_maintenance_items in 'tasks\tas_ext_maintenance_items.pas' {TasExtMaintenanceItems: TUniForm},
  fm_ext_motive in 'tasks\fm_ext_motive.pas' {FmExtMotive: TUniFrame},
  tas_generate_nfe in 'tasks\tas_generate_nfe.pas' {TasGenerateNfe: TUniForm},
  tas_generate_nfe_55 in 'tasks\tas_generate_nfe_55.pas' {TasGenerateNfe55: TUniForm},
  sea_ext_operating_test in 'tasks\sea_ext_operating_test.pas' {SeaExtOperatingTest: TUniForm},
  fm_collaborator in 'frames\fm_collaborator.pas' {FmCollaborator: TUniFrame},
  sea_service in 'files\sea_service.pas' {SeaService: TUniForm},
  auto_center_module in 'modules\auto_center_module.pas' {AutoCenterModule: TUniFrame},
  tas_ext_operating_test in 'tasks\tas_ext_operating_test.pas' {TasExtOperatingTest: TUniForm},
  cad_veh_brand_model in 'files\cad_veh_brand_model.pas' {CadVehBrandModel: TUniForm},
  tas_bank_activity in 'tasks\tas_bank_activity.pas' {TasBankActivity: TUniForm},
  tas_config_order_sale in 'tasks\tas_config_order_sale.pas',
  tas_config_g_product in 'tasks\tas_config_g_product.pas',
  tas_config in 'tasks\tas_config.pas' {TasConfig: TUniForm},
  fm_shipping in 'frames\fm_shipping.pas' {FmShipping: TUniFrame},
  cad_tax_cofins in 'files\cad_tax_cofins.pas' {CadTaxCofins: TUniForm},
  sea_veh_maintenance in 'tasks\sea_veh_maintenance.pas' {SeaVehMaintenance: TUniForm},
  tas_lot_ctrl in 'tasks\tas_lot_ctrl.pas' {TasLotCtrl: TUniForm},
  sea_serie_ctrl in 'files\sea_serie_ctrl.pas' {SeaSerieCtrl: TUniForm},
  tas_virtual_shop in 'tasks\tas_virtual_shop.pas' {TasVirtualShop: TUniForm},
  tas_send_email_marketing in 'tasks\tas_send_email_marketing.pas' {TasSendEmailMarketing: TUniForm},
  cad_veh_kind in 'files\cad_veh_kind.pas' {CadVehKind: TUniForm},
  sea_veh_kind in 'files\sea_veh_kind.pas' {SeaVehKind: TUniForm},
  sea_veh_brand_model in 'files\sea_veh_brand_model.pas' {SeaVehBrandModel: TUniForm},
  tas_copy_invoice in 'tasks\tas_copy_invoice.pas' {TasCopyInvoice: TUniForm},
  edi_financial in 'files\edi_financial.pas' {EdiFinancial: TUniForm},
  fm_financial in 'frames\fm_financial.pas' {FmFinancial: TUniFrame},
  cad_financial_bills in 'files\cad_financial_bills.pas' {CadFinancialBills: TUniForm},
  cad_financial_payment in 'files\cad_financial_payment.pas' {CadFinancialPayment: TUniForm},
  cad_financial in 'files\cad_financial.pas' {CadFinancial: TUniForm},
  base_impressao in 'repository\base_impressao.pas' {BaseImpressao: TUniForm},
  print_product in 'reports\print_product.pas' {PrintProduct: TUniForm},
  print_entities in 'reports\print_entities.pas' {PrintEntities: TUniForm},
  print_financial_bills in 'reports\print_financial_bills.pas' {PrintFinancialBills: TUniForm},
  print_financial_payment in 'reports\print_financial_payment.pas' {PrintFinancialPayment: TUniForm},
  print_invoice in 'reports\print_invoice.pas' {PrintInvoice: TUniForm},
  print_order_list in 'reports\print_order_list.pas' {PrintOrderList: TUniForm},
  cad_product_has_self in 'files\cad_product_has_self.pas' {CadProductHasSelf: TUniForm},
  sea_work_front in 'files\sea_work_front.pas' {SeaWorkFront: TUniForm},
  cad_work_front in 'files\cad_work_front.pas' {CadWorkFront: TUniForm},
  fm_work_front in 'frames\fm_work_front.pas' {FmWorkFront: TUniFrame},
  tas_order_job_scope in 'files\tas_order_job_scope.pas' {TasOrderJobScope: TUniForm},
  cad_med_price_list_jr in 'files\cad_med_price_list_jr.pas' {CadMedPriceListJR: TUniForm},
  cad_med_price_list_rt in 'files\cad_med_price_list_rt.pas' {CadMedPriceListRt: TUniForm},
  cad_med_price_list_ol in 'files\cad_med_price_list_ol.pas' {CadMedPriceListOl: TUniForm},
  sea_order_sale_salesman in 'tasks\sea_order_sale_salesman.pas' {SeaOrderSaleSalesman: TUniForm},
  tas_order_production_v2 in 'tasks\tas_order_production_v2.pas' {TasOrderProductionV2: TUniForm},
  sea_order_production_v2 in 'tasks\sea_order_production_v2.pas' {SeaOrderProductionV2: TUniForm},
  tas_order_items in 'tasks\tas_order_items.pas' {TasOrderItems: TUniForm},
  cad_su_institution in 'files\cad_su_institution.pas' {CadSuInstitution: TUniForm},
  tas_config_nfe in 'tasks\tas_config_nfe.pas' {TasConfigNfe: TUniForm},
  fm_nfe_events in 'frames\fm_nfe_events.pas' {FmNfeEvents: TUniFrame},
  print_financial_manager in 'reports\print_financial_manager.pas' {PrintFinancialManager: TUniForm},
  tblOrderItemIpi in 'model\tblOrderItemIpi .pas',
  cad_salesman in 'files\cad_salesman.pas' {CadSalesman: TUniForm},
  fm_devices in 'frames\fm_devices.pas' {FmDEvices: TUniFrame},
  sea_med_parts in 'tasks\sea_med_parts.pas' {SeaMedParts: TUniForm},
  tas_financial_bills_media in 'tasks\tas_financial_bills_media.pas' {TasFinancialBillsMedia: TUniForm},
  cad_financial_edit in 'files\cad_financial_edit.pas' {CadFinancialEdit: TUniForm},
  cad_financial_baixa in 'files\cad_financial_baixa.pas' {CadFinancialBaixa: TUniForm},
  sea_interation in 'tasks\sea_interation.pas' {SeaInteration: TUniForm},
  sea_iteration in 'tasks\sea_iteration.pas' {SeaIteration: TUniForm},
  project_module in 'modules\project_module.pas' {ProjectModule: TUniFrame},
  tblDskPromotion in 'D:\Gestao2016\module\tblDskPromotion.pas',
  tblDskPromotionItems in 'D:\Gestao2016\module\tblDskPromotionItems.pas',
  cad_interation_proposal in 'files\cad_interation_proposal.pas' {CadInterationProposal: TUniForm},
  cad_interation_task in 'files\cad_interation_task.pas' {CadinterationTask: TUniForm},
  cad_interation in 'files\cad_interation.pas' {CadInteration: TUniForm},
  cad_priority in 'files\cad_priority.pas' {CadPriority: TUniForm},
  sea_user in 'files\sea_user.pas' {SeaUser: TUniForm},
  sea_priority in 'files\sea_priority.pas' {SeaPriority: TUniForm},
  cad_project in 'files\cad_project.pas' {CadProject: TUniForm},
  sea_kind in 'files\sea_kind.pas' {SeaKind: TUniForm},
  sea_project in 'files\sea_project.pas' {SeaProject: TUniForm},
  cad_kind in 'files\cad_kind.pas' {CadKind: TUniForm},
  cad_situation in 'files\cad_situation.pas' {CadSituation: TUniForm},
  fm_priority in 'frames\fm_priority.pas' {FmPriority: TUniFrame},
  fm_User in 'frames\fm_User.pas' {FmUser: TUniFrame},
  fm_project in 'frames\fm_project.pas' {FmProject: TUniFrame},
  fm_kind in 'frames\fm_kind.pas' {FmKind: TUniFrame},
  cad_interation_progress in 'files\cad_interation_progress.pas' {CadInterationProgress: TUniForm},
  Sea_promotion in 'tasks\Sea_promotion.pas' {SeaPromotion: TUniForm},
  Cad_Promotion in 'tasks\Cad_Promotion.pas' {CadPromotion: TUniForm},
  das_sale in 'tasks\das_sale.pas' {DasSale: TUniForm},
  tas_financial_bills_general in 'tasks\tas_financial_bills_general.pas' {TasFinancialBillsGeneral: TUniForm},
  uniGUIApplication,
  System.Classes {TasFinancialBillsGeneral: TUniForm},
  test_module in 'modules\test_module.pas' {TestModule: TUniFrame},
  clinic_module in 'modules\clinic_module.pas' {ClinicModule: TUniFrame},
  tblClinModule in 'model\tblClinModule.pas',
  ControllerClinModule in 'controller\ControllerClinModule.pas',
  cad_clin_module in 'files\cad_clin_module.pas' {CadClinModule: TUniForm},
  sea_clin_module in 'files\sea_clin_module.pas' {SeaClinModule: TUniForm},
  sea_clin_professional in 'files\sea_clin_professional.pas' {SeaClinProfessional: TUniForm},
  cad_clin_professional in 'files\cad_clin_professional.pas' {CadClinProfessional: TUniForm},
  ControllerClinProfessional in 'controller\ControllerClinProfessional.pas',
  tblClinProfessional in 'model\tblClinProfessional.pas',
  sea_clin_patient in 'files\sea_clin_patient.pas' {SeaClinPatient: TUniForm},
  fm_clin_module in 'frames\fm_clin_module.pas' {FmClinModule: TUniFrame},
  ControllerClinPatient in 'controller\ControllerClinPatient.pas',
  tblClinPatient in 'model\tblClinPatient.pas',
  cad_clin_patient in 'files\cad_clin_patient.pas' {CadClinPatient: TUniForm},
  tblClinProfessionalHasPatient in 'model\tblClinProfessionalHasPatient.pas',
  ControllerClinProfessionalHasPatient in 'controller\ControllerClinProfessionalHasPatient.pas',
  fm_clin_patient in 'frames\fm_clin_patient.pas' {FmClinPatient: TUniFrame},
  sea_clin_questionnaire in 'files\sea_clin_questionnaire.pas' {SeaClinQuestionnaire: TUniForm},
  cad_clin_questionnaire in 'files\cad_clin_questionnaire.pas' {CadClinQuestionnaire: TUniForm},
  fm_clin_professional in 'frames\fm_clin_professional.pas' {FmClinProfessional: TUniFrame},
  tblClinQuestionnaire in 'model\tblClinQuestionnaire.pas',
  ControllerClinQuestionnaire in 'controller\ControllerClinQuestionnaire.pas',
  tblClinQuestion in 'model\tblClinQuestion.pas',
  ControllerClinQuestion in 'controller\ControllerClinQuestion.pas',
  sea_clin_quiz in 'tasks\sea_clin_quiz.pas' {SeaClinQuiz: TUniForm},
  ControllerClinQuiz in 'controller\ControllerClinQuiz.pas',
  tblClinQuiz in 'model\tblClinQuiz.pas',
  tblClinAnwer in 'model\tblClinAnwer.pas',
  ControllerClinAnwer in 'controller\ControllerClinAnwer.pas',
  tas_clin_quiz in 'tasks\tas_clin_quiz.pas' {TasClinQuiz: TUniForm},
  tblLogOperation in 'model\tblLogOperation.pas',
  fm_clin_question in 'frames\fm_clin_question.pas' {FmClinQuestion: TUniFrame},
  tblUserHasPrivilege in 'model\tblUserHasPrivilege.pas',
  ControllerUserHasPrivilege in 'controller\ControllerUserHasPrivilege.pas',
  tas_user_has_privilege in 'tasks\tas_user_has_privilege.pas' {TasUserHasPrivilege: TUniForm},
  ControllerLogOperation in 'controller\ControllerLogOperation.pas',
  sea_log_operation in 'tasks\sea_log_operation.pas' {SeaLogOperation: TUniForm},
  tblMedCopyEdition in 'model\tblMedCopyEdition.pas',
  ControllerMedCopyEdition in 'controller\ControllerMedCopyEdition.pas',
  cad_med_copy_edition in 'files\cad_med_copy_edition.pas' {CadMedCopyEdition: TUniForm},
  fm_StateCity in 'frames\fm_StateCity.pas' {FmStateCity: TUniFrame},
  TblBroacasterHasCirculaton in 'model\TblBroacasterHasCirculaton.pas',
  ControllerBroacasterHasCirculation in 'controller\ControllerBroacasterHasCirculation.pas',
  cad_med_broadcaster_circulation in 'files\cad_med_broadcaster_circulation.pas' {CadMedBroadcasterCirculation: TUniForm},
  intBroadcasterHasCirculation in 'Interface\intBroadcasterHasCirculation.pas',
  img_view in 'tasks\img_view.pas' {ImgView: TUniForm},
  tblUserSendEmail in 'model\tblUserSendEmail.pas',
  ControllerUserSendEmail in 'controller\ControllerUserSendEmail.pas',
  uReportFinancialCC in 'restClient\apiReport\uReportFinancialCC.pas',
  uReportGeneralCC in 'restClient\apiReport\uReportGeneralCC.pas',
  sea_order_budg_advertise in 'tasks\sea_order_budg_advertise.pas' {SeaOrderBudgAdvertise: TUniForm},
  tas_order_budg_advertise in 'tasks\tas_order_budg_advertise.pas' {TasOrderBudgAdvertise: TUniForm},
  tas_whatsapp_web in 'tasks\tas_whatsapp_web.pas' {TasWhatsappWeb: TUniForm},
  tblWhatsapp in 'model\tblWhatsapp.pas',
  ControllerWhatsapp in 'controller\ControllerWhatsapp.pas',
  tblWhatsappHasContact in 'model\tblWhatsappHasContact.pas',
  ControllerWhatsappHasContact in 'controller\ControllerWhatsappHasContact.pas',
  tblWhatsappHasTalk in 'model\tblWhatsappHasTalk.pas',
  ControllerWhatsappHasTalk in 'controller\ControllerWhatsappHasTalk.pas',
  tas_whatsapp_talk in 'tasks\tas_whatsapp_talk.pas' {TasWhatsappTalk: TUniFrame},
  cad_rest_menu in 'files\cad_rest_menu.pas' {CadRestMenu: TUniForm},
  sea_rest_menu in 'files\sea_rest_menu.pas' {SeaRestMenu: TUniForm},
  sea_rest_menu_pizza in 'files\sea_rest_menu_pizza.pas' {SeaRestMenuPizza: TUniForm},
  sea_rest_menu_beverage in 'files\sea_rest_menu_beverage.pas' {SeaRestMenuBeverage: TUniForm},
  pizzaria_module in 'modules\pizzaria_module.pas' {PizzariaModule: TUniFrame},
  ControllerRestMenu in 'controller\ControllerRestMenu.pas',
  cad_delivery_range in 'files\cad_delivery_range.pas' {CadDeliveryRange: TUniForm},
  tblDeliveryRange in 'model\tblDeliveryRange.pas',
  ControllerDeliveryRange in 'controller\ControllerDeliveryRange.pas',
  whatsAppWeb in 'function\whatsAppWeb.pas';

{$R *.res}

{$ifndef UNIGUI_VCL}

exports
  GetExtensionVersion,
  HttpExtensionProc,
  TerminateExtension;
{$endif}

begin
//{$ifdef UNIGUI_VCL}
  {$IFDEF DEBUG}
  //FullDebugModeScanMemoryPoolBeforeEveryOperation := True;
  ReportMemoryLeaksOnShutdown := True;
  //SuppressMessageBoxes := FAlse;
  {$ENDIF}
  Application.Initialize;
  TUSM.Create(Application);
  Application.Run;

//  {$endif}
end.
