program ApiData;
{$APPTYPE GUI}

uses
  {$IFDEF DEBUG}
  {$ENDIF }
  Vcl.Forms,
  Web.WebReq,
  IdHTTPWebBrokerBridge,
  uMain in 'uMain.pas' {Main},
  MainModule in 'MainModule.pas' {SC: TDataModule},
  uWM in 'uWM.pas' {WM: TWebModule},
  CAtribEntity in '..\framework\CAtribEntity.pas',
  GenericDao in '..\framework\GenericDao.pas',
  GenericEntity in '..\framework\GenericEntity.pas',
  UnFunctions in 'function\UnFunctions.pas',
  unmessages in 'function\unmessages.pas',
  list_spl_customer in '..\list\list_spl_customer.pas',
  TypesListCollection in '..\list\TypesListCollection.pas',
  list_spl_merchandise in '..\list\list_spl_merchandise.pas',
  list_spl_order_sale in '..\list\list_spl_order_sale.pas',
  UnitConstantes in '..\Classes\UnitConstantes.pas',
  UnitCep in '..\Classes\UnitCep.pas',
  UnTrataExcecao in 'function\UnTrataExcecao.pas',
  uSMAdvertiser in 'uSMAdvertiser.pas',
  uSMAgency in 'uSMAgency.pas',
  uSMBankAccount in 'uSMBankAccount.pas',
  uSMBrand in 'uSMBrand.pas',
  uSMBroadcaster in 'uSMBroadcaster.pas',
  uSMCategory in 'uSMCategory.pas',
  uSMCity in 'uSMCity.pas',
  uSMContact in 'uSMContact.pas',
  USMCountry in 'USMCountry.pas',
  uSMCustomer in 'uSMCustomer.pas',
  uSMFinancial in 'uSMFinancial.pas',
  uSMFinancialBills in 'uSMFinancialBills.pas',
  uSMFinancialPlans in 'uSMFinancialPlans.pas',
  uSMFinancialStatement in 'uSMFinancialStatement.pas',
  uSMInstitution in 'uSMInstitution.pas',
  uSMInvoice in 'uSMInvoice.pas',
  uSMLineBusiness in 'uSMLineBusiness.pas',
  uSMMeasure in 'uSMMeasure.pas',
  uSMMedMaterial in 'uSMMedMaterial.pas',
  uSMMedPosProg in 'uSMMedPosProg.pas',
  uSMMedPriceJR in 'uSMMedPriceJR.pas',
  uSMMerchandise in 'uSMMerchandise.pas',
  uSMOrderPI in 'uSMOrderPI.pas',
  uSMOrderSale in 'uSMOrderSale.pas',
  uSMPackage in 'uSMPackage.pas',
  uSMPaymentTypes in 'uSMPaymentTypes.pas',
  uSMPrice in 'uSMPrice.pas',
  uSMPriceList in 'uSMPriceList.pas',
  uSMProduct in 'uSMProduct.pas',
  uSMSalesMan in 'uSMSalesMan.pas',
  uSMServices in 'uSMServices.pas',
  uSMState in 'uSMState.pas',
  uSMStock in 'uSMStock.pas',
  uSMStockBalance in 'uSMStockBalance.pas',
  uSMStockList in 'uSMStockList.pas',
  uSMStockStatement in 'uSMStockStatement.pas',
  uSMEntityFiscal in 'uSMEntityFiscal.pas',
  uSMCashier in 'uSMCashier.pas',
  objCashier in '..\DataObjetcs\objCashier.pas',
  uSMPromotion in 'uSMPromotion.pas',
  uSMPromotionItems in 'uSMPromotionItems.pas',
  tblpromotionLog in '..\model\tblpromotionLog.pas',
  tblPromotionItemsLog in '..\model\tblPromotionItemsLog.pas',
  tblDskPromotionItems in 'D:\Gestao2016\module\tblDskPromotionItems.pas',
  uSMInvoiceMerchandise in 'uSMInvoiceMerchandise.pas',
  tblDskPromotion in 'D:\Gestao2016\module\tblDskPromotion.pas',
  tblOrderItemIpi in '..\model\tblOrderItemIpi.pas',
  tblSalesmanHasStock in '..\model\tblSalesmanHasStock.pas',
  tblSalesmanHasState in '..\model\tblSalesmanHasState.pas',
  ControllerSalesmanHasStock in '..\controller\ControllerSalesmanHasStock.pas',
  ControllerSalesmanHasState in '..\controller\ControllerSalesmanHasState.pas',
  uSMOrderConsignment in 'uSMOrderConsignment.pas',
  objOrderConsignment in '..\DataObjetcs\objOrderConsignment.pas',
  prm_order_consignment in '..\parameter\prm_order_consignment.pas',
  uSMKickback in 'uSMKickback.pas',
  objKickback in '..\DataObjetcs\objKickback.pas',
  objImages in '..\DataObjetcs\objImages.pas',
  uSM in 'uSM.pas' {SM: TDataModule},
  prm_financial in '..\parameter\prm_financial.pas',
  objFile in '..\DataObjetcs\objFile.pas',
  uSMInvoiceReturnService in 'uSMInvoiceReturnService.pas',
  objInvoiceReturnService in '..\DataObjetcs\objInvoiceReturnService.pas',
  tblProvisionalReceiptService in '..\model\tblProvisionalReceiptService.pas',
  ControllerProvisionalReceiptService in '..\controller\ControllerProvisionalReceiptService.pas',
  uSMInvoiceRectification in 'uSMInvoiceRectification.pas',
  tblEntitySeq in '..\model\tblEntitySeq.pas',
  ControllerEntitySeq in '..\controller\ControllerEntitySeq.pas',
  ControllerMailingSeq in '..\controller\ControllerMailingSeq.pas',
  tblMailingSeq in '..\model\tblMailingSeq.pas',
  uSMOrderPurchase in 'uSMOrderPurchase.pas',
  objOrderPurchase in '..\DataObjetcs\objOrderPurchase.pas',
  objProvider in '..\DataObjetcs\objProvider.pas',
  prm_order_purchase in '..\parameter\prm_order_purchase.pas',
  list_spl_order_purchase in '..\list\list_spl_order_purchase.pas',
  uSMOrderStockAdjust in 'uSMOrderStockAdjust.pas',
  list_spl_order_stock_adjust in '..\list\list_spl_order_stock_adjust.pas',
  prm_order_stock_adjust in '..\parameter\prm_order_stock_adjust.pas',
  objOrderStockAdjust in '..\DataObjetcs\objOrderStockAdjust.pas',
  objPackage in '..\DataObjetcs\objPackage.pas',
  objMeasure in '..\DataObjetcs\objMeasure.pas',
  prm_product in '..\parameter\prm_product.pas',
  list_spl_product in '..\list\list_spl_product.pas',
  prm_package in '..\parameter\prm_package.pas',
  prm_institution in '..\parameter\prm_institution.pas',
  prm_cashier in '..\parameter\prm_cashier.pas',
  prm_cashier_items in '..\parameter\prm_cashier_items.pas',
  prm_brand in '..\parameter\prm_brand.pas',
  prm_city in '..\parameter\prm_city.pas',
  prm_country in '..\parameter\prm_country.pas',
  prm_state in '..\parameter\prm_state.pas',
  prm_measure in '..\parameter\prm_measure.pas',
  prm_price in '..\parameter\prm_price.pas',
  prm_stock in '..\parameter\prm_stock.pas',
  prm_stock_balance in '..\parameter\prm_stock_balance.pas',
  prm_stock_statement in '..\parameter\prm_stock_statement.pas',
  prm_entity in '..\parameter\prm_entity.pas',
  prm_promotion in '..\parameter\prm_promotion.pas',
  prm_kickback in '..\parameter\prm_kickback.pas',
  prm_salesman_has_stock in '..\parameter\prm_salesman_has_stock.pas',
  uSMInvoiceReturn55 in 'uSMInvoiceReturn55.pas',
  uSMInvoiceReturn65 in 'uSMInvoiceReturn65.pas',
  uSMRestMenu in 'uSMRestMenu.pas',
  ObjRestMenu in '..\DataObjetcs\ObjRestMenu.pas',
  tblRestMenuHasProduct in '..\model\tblRestMenuHasProduct.pas',
  ControllerRestMenuHasProduct in '..\controller\ControllerRestMenuHasProduct.pas',
  uSMRestMenuHasIngredient in 'uSMRestMenuHasIngredient.pas',
  uSMRestGroup in 'uSMRestGroup.pas',
  uSMRestSubgroup in 'uSMRestSubgroup.pas',
  uSMRestGroupHasMeasure in 'uSMRestGroupHasMeasure.pas',
  uSMRestGroupHasOptional in 'uSMRestGroupHasOptional.pas',
  uSMProvider in 'uSMProvider.pas',
  prm_provider in '..\parameter\prm_provider.pas',
  list_spl_provider in '..\list\list_spl_provider.pas',
  tblNoDocNumber in '..\model\tblNoDocNumber.pas',
  ControllerNoDocNumber in '..\controller\ControllerNoDocNumber.pas';

{$R *.res}

begin
  {$IFDEF DEBUG}
  //FullDebugModeScanMemoryPoolBeforeEveryOperation := True;
  ReportMemoryLeaksOnShutdown := True;
  //SuppressMessageBoxes := FAlse;
  {$ENDIF}
  if WebRequestHandler <> nil then
    WebRequestHandler.WebModuleClass := WebModuleClass;
  Application.Initialize;
  Application.CreateForm(TMain, Main);
  Application.Run;
end.
